version: "3"

services: 
    backend:
        container_name: "mern-backend"
        build: ./backend
        ports: 
            - "3000:3000"
    
    database:
        container_name: mongo
        image: mongo
        volumes: 
            - .data:/data/db
        ports: 
            - "27018:27017"    
