version: "3"

services: 
    backend:
        container_name: "mern-backend"
        build: ./backend
        ports: 
            - "8000:8000"
        networks: 
            - app-network    
        depends_on: 
            - database    
    
    database:
        container_name: mongo
        image: mongo
        volumes: 
            - .data:/data/db
            # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports: 
            - "27017:27017"    
        networks: 
            - app-network  
    
    frontend:
        container_name: "mern-frontend"
        build: ./frontend
        ports: 
            - "3000:3000"
        networks: 
            - app-network
                       

networks:
    app-network:
        driver: bridge
            